name: mkdocs-build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: '1.5.3'      # match mkdocs-material~=1.5.3
          requirements: 'requirements.txt'
          configfile: 'mkdocs.yml'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          allow_empty_commit: true

- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.x'

- name: Cache pip packages
  uses: actions/cache@v4
  with:
    path: ~/.cache/pip
    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    restore-keys: |
      ${{ runner.os }}-pip-

- name: Install Python dependencies
  run: |
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then
      pip install -r requirements.txt
    else
      # Install at least mkdocs and the glightbox plugin
      pip install mkdocs mkdocs-material mkdocs-glightbox
    fi
